const assert=require('assert');
const fs=require('fs');
const os=require('os');
const path=require('path');
const {RunningHostIdentityService,parseDesignatedRequirement}=require('../desktop/app/src/context/running-host-identity');
(async()=>{
assert.equal(parseDesignatedRequirement('Executable=/tmp/X.app\n   designated => identifier "com.sidedock.desktop" and info[CFBundleIdentifier] = "com.sidedock.desktop"\n'), 'identifier "com.sidedock.desktop" and info[CFBundleIdentifier] = "com.sidedock.desktop"');
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'sidedock-r3-id-'));
const app=path.join(tmp,'SideDock.app');
const execPath=path.join(app,'Contents','MacOS','Electron');
const hostRoot=path.join(app,'Contents','Resources','app');
const support=path.join(tmp,'support');
fs.mkdirSync(path.dirname(execPath),{recursive:true}); fs.mkdirSync(hostRoot,{recursive:true}); fs.mkdirSync(support,{recursive:true});
fs.writeFileSync(execPath,'electron'); fs.writeFileSync(path.join(hostRoot,'bootstrap.js'),'bootstrap');
fs.writeFileSync(path.join(hostRoot,'HOST_ABI.json'),JSON.stringify({hostAbi:1,hostGeneration:'H1',freezeContract:'sidedock-h1-freeze/1',bundleId:'com.sidedock.desktop'}));
const req='identifier "com.sidedock.desktop" and info[CFBundleIdentifier] = "com.sidedock.desktop"';
const display='Executable='+app+'\ndesignated => '+req+'\n';
const detail='Identifier=com.sidedock.desktop\nCDHash=abc123\nTeamIdentifier=not set\n';
const runCommand=async(_file,args)=>{ if(args.includes('-r-')) return {error:null,stdout:'',stderr:display}; if(args.includes('-dv')) return {error:null,stdout:'',stderr:detail}; if(args.includes('-R')) return {error:null,stdout:'',stderr:''}; return {error:null,stdout:'',stderr:''}; };
const svc0=new RunningHostIdentityService({supportRoot:support,execPathProvider:()=>execPath,platform:'darwin',runCommand});
const first=await svc0.snapshot();
const receipt={contract:'sidedock-host-receipt/3',hostAbi:1,hostGeneration:'H1',freezeContract:'sidedock-h1-freeze/1',bundleId:'com.sidedock.desktop',canonicalAppPath:app,executableSha256:first.executableSha256,bootstrapSha256:first.bootstrapSha256,hostAbiSha256:first.hostAbiSha256,hostResourcesSha256:first.hostResourcesSha256,designatedRequirement:req,hostFingerprint:first.hostFingerprint,hostFrozen:true};
fs.writeFileSync(path.join(support,'HOST_RECEIPT.json'),JSON.stringify(receipt));
const fallbackRun=async(_file,args)=>{ if(args.includes('-r-')) return {error:null,stdout:'',stderr:'Executable='+app+'\n'}; if(args.includes('-R')) return {error:null,stdout:'',stderr:''}; if(args.includes('-dv')) return {error:null,stdout:'',stderr:detail}; return {error:null,stdout:'',stderr:''}; };
const svc=new RunningHostIdentityService({supportRoot:support,execPathProvider:()=>execPath,platform:'darwin',runCommand:fallbackRun});
const snap=await svc.snapshot();
assert.equal(snap.designatedRequirement,req); assert.equal(snap.designatedRequirementSource,'receipt_verified_expression'); assert.equal(snap.designatedRequirementVerified,true); assert.equal(snap.identityComparison.requirementMatch,true); assert.equal(snap.identityComparison.fingerprintMatch,true); assert.equal(snap.sameAsInstalledHost,true);
console.log('PASS v1.5.14 R3 running Host requirement verification fallback');
})().catch((e)=>{console.error(e);process.exit(1);});
